FisheryManagement/Analytics/urls.py
from django.urls import path
from . import views

app_name = "Analytics"

urlpatterns = [
    path('forms/', views.isforms, name="forms"),
    path('RecentList/', views.recentList, name="recentlist"),
    path('OverallCatchdash/', views.OCdash, name="OverallCatchdash"),
    path('unloadingDashData/', views.dataUnloadingDash, name="dataUnloadingDash"),
    path('FishCatchdash/', views.FCdash, name="FishCatchdash"),
    path('admindashboard/', views.isadmindashboard, name="admindashboard"),
    path('userstable/', views.userstable, name="userstable"),
    path('unloadHistory/', views.unloadhistory, name="unloadhistory"),
    path('edituser/<int:id>/', views.edit_user, name="edituser"),
    path('delete_user/<int:id>/', views.delete_user, name='delete_user'),
    path('edit/<int:id>/', views.edit_unloading, name='edit_unloading'),
    path('analytics/delete/<int:id>/', views.delete_unload_history, name='delete_unload_history'),
    path('edit-recentlist/<int:id>/', views.edit_recentlist, name='edit_recentlist'),
    path('delete-recentlist/<int:id>/', views.delete_recentlist, name='delete_recentlist'),

]

FisheryManagement/Authentication/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "Authentication"


urlpatterns = [
    path('PortManager', views.isLandingPage, name='landingPage'),
    path('MarketChecker', views.isMCLandingPage, name='MClandingPage'),
    path('login/', views.islogin, name='login'),
    path('register/', views.isreghtml, name='register'),
    path('pmlogin/', views.ispmloginhtml, name='pmlogin'),
    path('pmreg/', views.ispmreghtml, name='pmregister'),
    path('loginadmin/', views.isadminloginhtml, name='loginadmin'),
    path('regadmin/', views.isadminreghtml, name='registeradmin'),


    # Password Reset URLs
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

FisheryManagement/FisheryManagement/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
     path('admin', admin.site.urls),
     path('auth/', include('Authentication.urls', namespace='Authentication')),

     path('analytics/', include('Analytics.urls')),
]

FisheryManagement/Analytics/models.py
from django.db import models

class Categories(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name 
    

class Species(models.Model):
    species_name = models.CharField(max_length=50, unique=True)
    category = models.ForeignKey(Categories, on_delete=models.CASCADE, related_name='species')
    quantity = models.IntegerField(default=0)

    def __str__(self):
        return self.species_name


class unloadType(models.Model):
    unloadTypeName = models.CharField(max_length=30)


class Origin(models.Model):
    origin = models.CharField(max_length=30)

    def __str__(self):
        return self.origin
    

class Vessel(models.Model):
    vessel_name = models.CharField(max_length=30)
    origin = models.ForeignKey(Origin, on_delete=models.CASCADE)
    unloadType = models.ForeignKey(unloadType,on_delete=models.CASCADE,null=True)

    def __str__(self):
        return self.vessel_name
 
class DailyTransaction(models.Model):
    species = models.ForeignKey(Species, on_delete=models.CASCADE)
    origin = models.ForeignKey(Origin, on_delete=models.CASCADE, null=True)
    vessel = models.ForeignKey(Vessel, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    date = models.DateField()
    unloadType = models.ForeignKey(unloadType,on_delete=models.CASCADE,null=True)


    def __str__(self):
        return f'{self.species}'

FisheryManagement/Analytics/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group
from .models import Species, unloadType, Origin, Vessel, DailyTransaction
from django.http import JsonResponse
from collections import defaultdict
from django.db.models import Sum
from django.db.models.functions import TruncMonth, TruncYear
from datetime import datetime
from django.db.models import Q
from django.core.paginator import Paginator
from django.utils import timezone
from django.db import IntegrityError
from django.db.models import Max
from django.views.decorators.http import require_GET
from django.http import HttpResponse
from django.core.exceptions import ValidationError
from django.contrib import messages

from django.core.exceptions import MultipleObjectsReturned


""" TO GET DATA FROM THE FORMS """


@login_required(login_url='Authentication:MClandingPage')
def isforms(request):
    origins = Origin.objects.all()
    species_list = Species.objects.all()

    if request.method == 'POST':
        fishtype = request.POST.get('fishtype')
        quantity = request.POST.get('quantity')
        vessel = request.POST.get('vessel')
        placeofcatch = request.POST.get('placeofcatch')
        unload_type_name = request.POST.get('typeofUnload')

        # Check for completeness of form data
        if not all([fishtype, quantity, vessel, placeofcatch, unload_type_name]):
            return render(request, 'MCforms.html', {
                'origins': origins,
                'species_list': species_list,
                'error_message': 'Please fill in all the required fields.'
            })

        origin = placeofcatch.capitalize()

        try:
            dateofCatch = timezone.now().strftime('%Y-%m-%d')

            # Create or get Origin
            origin_instance, _ = Origin.objects.get_or_create(
                origin=origin
            )
        except Origin.DoesNotExist:
            origin_instance = Origin.objects.create(
                origin=origin,
            )

        # Check if the species already exists
        existing_species = Species.objects.filter(species_name=fishtype).first()

        if existing_species:
            # Use the existing species instead of creating a new one
            species_instance = existing_species
        else:
            try:
                species_instance, _ = Species.objects.get_or_create(
                    species_name=fishtype,
                    quantity=quantity,
                )
            except IntegrityError:
                species_instance = Species.objects.get(species_name=fishtype)

        vessel_instance, _ = Vessel.objects.get_or_create(
            vessel_name=vessel,
            origin=origin_instance,
        )

        unload_type_instance, _ = unloadType.objects.get_or_create(unloadTypeName=unload_type_name)

        new_transaction = DailyTransaction(
            species=species_instance,
            quantity=quantity,
            vessel=vessel_instance,
            origin=origin_instance,
            date=dateofCatch,
            unloadType=unload_type_instance,
        )
        new_transaction.save()

        return HttpResponse('Form submitted successfully.')  # You can modify this as needed

    return render(request, 'MCforms.html', {
        'origins': origins,
        'species_list': species_list,
    })

@login_required(login_url='Authentication:MClandingPage')
def recentList(request):
    most_recent_date = DailyTransaction.objects.aggregate(max_date=Max('date'))['max_date']

    transactions = DailyTransaction.objects.filter(date=most_recent_date)

    search_query = request.GET.get('q')

    if search_query:
        transactions = transactions.filter(
            Q(species__species_name__icontains=search_query) |
            Q(quantity__icontains=search_query) |
            Q(vessel__vessel_name__icontains=search_query) |
            Q(origin__origin__icontains=search_query)
        )

    paginator = Paginator(transactions, 9)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    return render(request, 'recentlist.html', {'transactions': page, 'search_query': search_query})

""" FOR EDITING USER INFORMATION """
@login_required(login_url='Authentication:loginadmin')
def edit_user(request, id):
    user = get_object_or_404(User, id=id)
    if request.method == 'POST':
        first_name = request.POST.get('firstName')
        last_name = request.POST.get('lastName')
        email = request.POST.get('email')
        username = request.POST.get('username')
        usergroup = request.POST.get('usergroup')

        user.first_name = first_name
        user.last_name = last_name
        user.email = email
        if user.username:
            pass
        else:
            user.username = username
        user.group = usergroup

        group = Group.objects.get(name=usergroup)
        user.group = group

        user.save()

        return redirect('Analytics:userstable') 

    return render(request, 'edituser.html', {
        'user': user
    })

""" TO DELETE USER IN USER'S TABLE """
@login_required(login_url='Authentication:loginadmin')
def delete_user(request, id):
    user = get_object_or_404(User, id=id)
    user.delete()
    return redirect('Analytics:userstable')  

@login_required(login_url='Authentication:PortManager')
def OCdash(request):
    # Get unique origins directly from the database using distinct()
    unique_origins = Origin.objects.values('origin').distinct()

    # Rest of your code
    years = DailyTransaction.objects.dates('date', 'year').order_by('-date').distinct()
    unique_years_set = set(year.year for year in years)
    unique_years = list(unique_years_set)

    return render(request, 'OCDash.html', {'origins': unique_origins, 'unique_years': unique_years})

""" API FOR DATA COLLECTION AND GRAPHS """
@require_GET
def dataUnloadingDash(request):
    selected_fish_type = request.GET.get('fish_type', None)
    selected_month = request.GET.get('month', None)
    selected_year = request.GET.get('year', None)
    selected_origin = request.GET.get('origin', None)

    transactions = DailyTransaction.objects.filter(species__species_name=selected_fish_type) if selected_fish_type else DailyTransaction.objects.all()
    if selected_month:
        transactions = transactions.filter(date__month=selected_month)  
    if selected_year:
        transactions = transactions.filter(date__year=selected_year)
    if selected_origin:
        transactions = transactions.filter(origin__origin=selected_origin)

    # Calculate quantity by date
    quantity_by_date = defaultdict(int)
    for transaction in transactions:
        quantity_by_date[str(transaction.date)] += transaction.quantity

    # Calculate monthly and yearly catch
    monthly_catch = transactions.annotate(month=TruncMonth('date')).values('month').annotate(total_quantity=Sum('quantity'))
    yearly_catch = transactions.annotate(year=TruncYear('date')).values('year').annotate(total_quantity=Sum('quantity'))

    # Calculate quantities by species, origin, and vessel
    species_quantities = transactions.values('species__species_name').annotate(total_quantity=Sum('quantity'))
    origin_quantities = transactions.values('origin__origin').annotate(total_quantity=Sum('quantity'))
    vessel_quantities = transactions.values('vessel__vessel_name').annotate(total_quantity=Sum('quantity'))

    # Prepare data for labels and quantities
    labels_daily = []
    quantities = []
    species = []
    origins = []
    vessels = []

    unique_dates_set = set()  
    for transaction in transactions:
        date_str = transaction.date.strftime('%B %d, %Y')  
        if date_str not in unique_dates_set: 
            labels_daily.append(date_str) 
            quantities.append(quantity_by_date[str(transaction.date)]) 
            unique_dates_set.add(date_str) 
        species.append(transaction.species.species_name)
        origin_data = transaction.origin.origin if transaction.origin else None
        origins.append(origin_data)
        vessels.append(transaction.vessel.vessel_name)

    # Sort daily data based on date
    daily_data_sorted = sorted(zip(labels_daily, quantities, species, origins, vessels), key=lambda x: datetime.strptime(x[0], '%B %d, %Y'))
    labels_daily_sorted, quantities_sorted, species_sorted, origins_sorted, vessels_sorted = zip(*daily_data_sorted)

    # Prepare data for monthly and yearly catch
    labels_monthly = []
    quantities_monthly = []
    labels_yearly = []
    quantities_yearly = []

    for entry in monthly_catch:
        month = entry['month'].strftime('%b %Y')
        labels_monthly.append(month)  
        quantities_monthly.append(entry['total_quantity'])

    for entry in yearly_catch:
        year = entry['year'].strftime('%Y')
        labels_yearly.append(year)  
        quantities_yearly.append(entry['total_quantity'])

    # Prepare data for species, origin, and vessel quantities
    species_data = []
    for entry in species_quantities:
        species_data.append({
            'species_name': entry['species__species_name'],
            'total_quantity': entry['total_quantity'],
        })

    origin_data = []
    for entry in origin_quantities:
        origin_data.append({
            'origin': entry['origin__origin'],
            'total_quantity': entry['total_quantity'],
        })

    vessel_data = []
    for entry in vessel_quantities:
        vessel_data.append({
            'vessel_name': entry['vessel__vessel_name'],
            'total_quantity': entry['total_quantity'],
        })

    # Construct the response data
    data = {
        'labels_daily': labels_daily_sorted,
        'quantities': quantities_sorted,
        'labels_monthly': labels_monthly,
        'quantities_monthly': quantities_monthly,
        'labels_yearly': labels_yearly,
        'quantities_yearly': quantities_yearly,

FisheryManagement/Analytics/templates/FCDash.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  {% csrf_token %}
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/dash.css' %}">
  <link rel="stylesheet"href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
  <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <title>ISdaanIS:Fish Catch Rate</title>
</head>
<body>

  <nav>
     
      <!-- Code for the sidebar -->
      <div class="logo-name">
        <div class="logo-image">
            <img src="{% static 'img/pfda.png' %}" alt="">
        </div>
  
        <span class="logo_name">IsdaanIS</span>
    </div>
    <div class="menu-items">
        <ul class="nav-links"> 
            <li>
                <a href="{% url 'Analytics:OverallCatchdash' %}">
                  <i class="uil uil-chart-bar"></i>
                  <span class="link-name">Overall Catch</span>
              </a>
            </li>
            <li><a href="{% url 'Analytics:FishCatchdash' %}">
              <i class="uil uil-ship"></i>
                <span class="link-name">Fish Catch Rate</span>
            </a></li>
          </ul>    
          <ul class="logout-mode">
            <li>
              <a href="#" onclick="openLogoutModal()" data-logout-url="{% url 'Authentication:landingPage' %}">
                <i class="uil uil-signout"></i>
                <span class="link-name">Logout</span>
              </a>
            </li>
          </ul>
        

            <li class="mode">
                <a href="#">
                    <i class="uil uil-moon"></i>
                <span class="link-name">Dark Mode</span>
            </a>

            <div class="mode-toggle">
              <span class="switch"></span>
            </div>
        </li>
        </ul>
        
    </div>

   
</nav>

<div id="logoutModal" class="modal">
  <div class="modal-content">
    <span class="close" onclick="closeLogoutModal()">&times;</span>
    <p>Do you really want to log out?</p>
    <button onclick="logout()">Logout</button>
    <button onclick="closeLogoutModal()">Cancel</button>
  </div>
</div>
<div id="logoutSuccessMessage" class="logout-success-message" style="display:none;">
  Logout successful! <!-- You can customize this message -->
</div>
            <!-- Code for the graphs -->
<section class="dashboard">
      
        <div class="chart-container" width="100%" height="80">
          <h2>VESSEL</h2>
          <canvas id="Vessel"></canvas>
      </div>

      <div class="chart-container2" width="100%" height="80">
          <h2>PLACES</h2>
          <canvas id="PlaceOfCatch"></canvas>
      </div>
      
      
      <div class="chart-container3" width="100%" height="80">
        <h2>MONTHLY</h2>
        <canvas id="MonthlyCatch"></canvas>
      </div>
  
    
      
      <div class="chart-container4" width="100%" height="80">
        <h2>YEARLY</h2>
        <canvas id="YearlyCatch"></canvas>
      </div>
      

      
      
      
      <!-- code for sidebar toggle -->
    <div class="top">
        <i class="uil uil-bars sidebar-toggle"></i>
        <label for="fishtype">Type of Fish:</label>
            <select name="fishtype" id="fishtypeOptions">
              <option value="">Select Fish </option>
                {% for species in species_list %}
                    <option value="{{ species.species_name }}">{{ species.species_name }}</option>
                {% endfor %}
            </select>

            <label for="months">Choose a month:</label>
                <select name="months" id="months">
                  <option value="">Select Month</option>
                  <option value="01">January</option>
                  <option value="02">February</option>
                  <option value="03">March</option>
                  <option value="04">April</option>
                  <option value="05">May</option>
                  <option value="06">June</option>
                  <option value="07">July</option>
                  <option value="08">August</option>
                  <option value="09">September</option>
                  <option value="10">October</option>
                  <option value="11">November</option>
                  <option value="12">December</option>
                </select>


            <label for="year">Choose Year:</label>
              <select name="year" id="year">
                <option value="">Select Year </option>
                  {% for year in unique_years %}
                      <option value="{{ year }}">{{ year }}</option>
                  {% endfor %}
              </select>


    </section>

  
    
  </div>




<script src="{% static 'js/unloadingdash.js' %}"></script>


</body>
</html>

FisheryManagement/Analytics/templates/OCDash.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/dash.css' %}">
  <link rel="stylesheet"href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
  <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <title>ISdaanIS: Overall Catch</title>
</head>
<body>

  <nav>
    <div class="logo-name">
      <div class="logo-image">
          <img src="{% static 'img/pfda.png' %}" alt="">
      </div>

      <span class="logo_name">IsdaanIS</span>
  </div>
      <!-- Code for the sidebar -->
    <div class="menu-items">
        <ul class="nav-links">
            <li>
              <a href="{% url 'Analytics:OverallCatchdash' %}">
                <i class="uil uil-chart-bar"></i>
                <span class="link-name">Overall Catch</span>
            </a>
          </li>
          <li><a href="{% url 'Analytics:FishCatchdash' %}">
            <i class="uil uil-ship"></i>
              <span class="link-name">Fish Catch Rate</span>
          </a></li>
          </ul>    
          <ul class="logout-mode">
            <li>
              <a href="#" onclick="openLogoutModal()" data-logout-url="{% url 'Authentication:landingPage' %}">
                <i class="uil uil-signout"></i>
                <span class="link-name">Logout</span>
              </a>
            </li>
          </ul>
        

            <li class="mode">
                <a href="#">
                    <i class="uil uil-moon"></i>
                <span class="link-name">Dark Mode</span>
            </a>

            <div class="mode-toggle">
              <span class="switch"></span>
            </div>
        </li>
        </ul>
    </div>

</nav>


            <!-- Code for the graphs -->
<section class="dashboard">
  
      <div class="chart-container" width="100%" height="80">
        <h2>TYPES OF FISHES</h2>
        <canvas id="Fishtype"></canvas>
      </div>
      
      
      <div class="chart-container4" width="100%" height="80">
        <h2>DAILY </h2>
        <canvas id="DailyCatch"></canvas>
      </div>
      
      <div class="chart-container5" width="100%" height="80">
        <h2>MONTHLY</h2>
        <canvas id="MonthlyCatch"></canvas>
      </div>
      
      <div class="chart-container6" width="100%" height="80">
        <h2>YEARLY</h2>
        <canvas id="YearlyCatch"></canvas>
      </div>
      

      
      
      
      <!-- code for sidebar toggle -->
    <div class="top">
        <i class="uil uil-bars sidebar-toggle"></i>

        <label for="months">Choose a month:</label>
                <select name="months" id="months">
                  <option value="">Select Month</option>
                  <option value="01">January</option>
                  <option value="02">February</option>
                  <option value="03">March</option>
                  <option value="04">April</option>
                  <option value="05">May</option>
                  <option value="06">June</option>
                  <option value="07">July</option>
                  <option value="08">August</option>
                  <option value="09">September</option>
                  <option value="10">October</option>
                  <option value="11">November</option>
                  <option value="12">December</option>
                </select>


            <label for="year">Choose Year:</label>
              <select name="year" id="year">
                <option value="">Select Year </option>
                  {% for year in unique_years %}
                      <option value="{{ year }}">{{ year }}</option>
                  {% endfor %}
              </select>
    </div>
    
    </section>

  
    <div id="logoutModal" class="modal">
      <div class="modal-content">
        <span class="close" onclick="closeLogoutModal()">&times;</span>
        <p>Do you really want to log out?</p>
        <button onclick="logout()">Logout</button>
        <button onclick="closeLogoutModal()">Cancel</button>
      </div>
  </div>




<script src="{% static 'js/loadingdash.js' %}"></script>


</body>
</html>

FisheryManagement/Analytics/templates/admindash.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> IsdaanIS:Admin</title>
    <link rel="stylesheet" href="{% static 'css/Adashboard.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
   </head>
<body>
  <div class="main_box">
    <input type="checkbox" id="check">
    <div class="navbar">
    <h2>ISdaanIS</h2>
    <div class="btn_one">
      <label for="check">
        <i class='bx bx-menu'></i>
      </label>
    </div>

  </div>
    <div class="sidebar_menu">
      <div class="logo">
        <div class="logo-image">
          <img src="{% static 'img/pfda.png' %}" alt="">
          <a href="#">IsdaanIS</a>
      </div>
        
          </div>
        <div class="btn_two">
          <label for="check">
            <i class='bx bx-x'></i>
          </label>
        </div>
      <div class="menu">
        <ul>
          <li>
            <a href="{% url 'Analytics:userstable'%}">
              <i class='bx bxs-user'></i>Users</a>
          </li>
          <li>
            <a href="{% url 'Analytics:unloadhistory'%}">
              <i class='bx bx-line-chart'></i>Unload History</a>
          </li>
          <li>
            <a href="#" onclick="openLogoutModal()">
              <i class='bx bx-exit'></i>Logout</a>
          </li>
        </ul>
      </div>
    </div>

    
      <div class="boxes">
        <div class="box box2 tui">
            <i class="uil uil-thumbs-up"></i>
            <span class="text">Total Unloading Input</span>
            <span class="number">{{ total_number_of_inputs }}</span>
        </div>
    </div>
    
    <div class="boxes">
        <div class="box box2 tf">
            <i class="uil uil-thumbs-up"></i>
            <span class="text">Top 10 Fishes</span>
            <span class="number">
                <ul>
                    {% for fish in top_fishes %}
                    <li>{{ fish.species__species_name }} - {{ fish.total_quantity }}</li>
                    {% endfor %}
                </ul>
            </span>
        </div>
    
        <div class="box box2 tv">
            <i class="uil uil-comments"></i>
            <span class="text">Top 10 Vessels</span>
            <span class="number">
                <ul>
                    {% for vessel in top_vessels %}
                    <li>{{ vessel.vessel__vessel_name }} - {{ vessel.total_quantity }}</li>
                    {% endfor %}
                </ul>
            </span>
        </div>
    
        <div class="box box2 tfo">
            <i class="uil uil-comments"></i>
            <span class="text">Top 10 Fishes origins</span>
            <span class="number">
                <ul>
                    {% for origin in top_origins %}
                    <li>{{ origin.origin__origin }} - {{ origin.total_quantity }}</li>
                    {% endfor %}
                </ul>
            </span>
        </div>
    </div>
  

<div id="logoutModal" class="modal">
  <div class="modal-content">
    <span class="close" onclick="closeLogoutModal()">&times;</span>
    <p>Are you sure you want to logout?</p>
    <button onclick="cancelLogout()">Cancel</button>
    <a id="logoutLink" href="{% url 'Authentication:loginadmin' %}">Logout</a>
  </div>
</div>
</div>


<script src="{% static 'js/adminDash.js' %}"></script>
  </body>

</html>

FisheryManagement/Analytics/templates/recentlist.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Recent List</title>
  <link rel="stylesheet" href="{% static 'css/recentlist.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
</head>
<body>
  
  <div class="navbar">
    <h2>MARKET CHECKER RECENT DATA INPUT</h2>
    <div class="dropdown">
        <button class="dropbtn">Menu</button>
        <div class="dropdown-content">
            <!-- Add other menu items if needed -->
            <a href="{% url 'Analytics:forms' %}">Add New Data</a>
            <a href="#" id="logoutButton" data-logout-url="{% url 'Authentication:MClandingPage' %}" class="text-decoration-none fs-4 text-dark">LOGOUT</a>
          </div>
        </div>
        <div id="logoutModal" class="modal">
          <div class="modal-content">
              <span class="close" onclick="closeModal()">&times;</span>
              <p>Are you sure you want to logout?</p>
              <button id="confirmLogout" onclick="performLogout()">Logout</button>
              <button id="cancelLogout" onclick="closeModal()">Cancel</button>
          </div>
      </div>
      
      
    </div>

    
    <div class="table-responsive bg-secondary">
      <div class="topbar">
        <form id="search-form" method="get">
            <div class="search-bar">
                <input type="text" id="search-input" name="q" placeholder="Search.." {% if search_query %}value="{{ search_query }}"{% endif %}>
                <button type="submit" id="search-btn" class="btn">
                    <i class='bx bx-search-alt-2'></i>
                </button>
            </div>
        </form>
       
    </div>
        <table class="table table-bordered table-hover ">
            <thead>
              <!-- Table Contents -->
              <tr class="bg-secondary">
                <th scope="col">Load Date</th>
                <th scope="col">Category</th>
                <th scope="col">Type of fish</th>
                <th scope="col">Quantity</th>
                <th scope="col">Vessel</th>
                <th scope="col">Type of Unloading</th>
                <th scope="col">Location</th>
                <th scope="col">Actions</th>


            
              </tr>
            </thead>
            <!-- Table Data -->
            <tbody>
              {% for transaction in transactions %}
              <tr> 
                <td>{{ transaction.date }}</td>
                <td>{{ transaction.species.category.name }}</td>
                <td>{{ transaction.species.species_name }}</td>
                <td>{{ transaction.quantity }}</td>
                <td>{{ transaction.vessel.vessel_name }}</td>
                <td>{{ transaction.unloadType.unloadTypeName }}</td> 
                <td>{{ transaction.origin.origin }}</td>
                <td class="table-info">
                  <a href="{% url 'Analytics:edit_recentlist' id=transaction.id %}"><button class="btn btn-primary">Edit</button></a>
                  <a href="{% url 'Analytics:delete_recentlist' id=transaction.id %}" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this entry?')">Delete</a>


                  
              </td>

              </tr>
              {% endfor %}
            </tbody>
        </table>
  </div>

  <div class="pagination">
    <span class="step-links">
        {% if transactions.has_previous %}
            <a href="?page=1{% if search_query %}&q={{ search_query }}{% endif %}">&laquo; first</a>
            <a href="?page={{ transactions.previous_page_number }}{% if search_query %}&q={{ search_query }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ transactions.number }} of {{ transactions.paginator.num_pages }}.
        </span>

        {% if transactions.has_next %}
            <a href="?page={{ transactions.next_page_number }}{% if search_query %}&q={{ search_query }}{% endif %}">next</a>
            <a href="?page={{ transactions.paginator.num_pages }}{% if search_query %}&q={{ search_query }}{% endif %}">last &raquo;</a>
        {% endif %}
    </span>
</div>




  <script src="{% static 'js/recentlist.js' %}"></script>
</body>
</html>