FisheryManagement/Analytics/urls.py
from django.urls import path
from . import views

app_name = "Analytics"

urlpatterns = [
    path('forms/', views.isforms, name="forms"),
    path('RecentList/', views.recentList, name="recentlist"),
    path('OverallCatchdash/', views.OCdash, name="OverallCatchdash"),
    path('unloadingDashData/', views.dataUnloadingDash, name="dataUnloadingDash"),
    path('FishCatchdash/', views.FCdash, name="FishCatchdash"),
    path('admindashboard/', views.isadmindashboard, name="admindashboard"),
    path('userstable/', views.userstable, name="userstable"),
    path('unloadHistory/', views.unloadhistory, name="unloadhistory"),
    path('edituser/<int:id>/', views.edit_user, name="edituser"),
    path('delete_user/<int:id>/', views.delete_user, name='delete_user'),
    path('edit/<int:id>/', views.edit_unloading, name='edit_unloading'),
    path('analytics/delete/<int:id>/', views.delete_unload_history, name='delete_unload_history'),
    path('edit-recentlist/<int:id>/', views.edit_recentlist, name='edit_recentlist'),
    path('delete-recentlist/<int:id>/', views.delete_recentlist, name='delete_recentlist'),

]

FisheryManagement/Authentication/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "Authentication"


urlpatterns = [
    path('PortManager', views.isLandingPage, name='landingPage'),
    path('MarketChecker', views.isMCLandingPage, name='MClandingPage'),
    path('login/', views.islogin, name='login'),
    path('register/', views.isreghtml, name='register'),
    path('pmlogin/', views.ispmloginhtml, name='pmlogin'),
    path('pmreg/', views.ispmreghtml, name='pmregister'),
    path('loginadmin/', views.isadminloginhtml, name='loginadmin'),
    path('regadmin/', views.isadminreghtml, name='registeradmin'),


    # Password Reset URLs
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

FisheryManagement/FisheryManagement/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
     path('admin', admin.site.urls),
     path('auth/', include('Authentication.urls', namespace='Authentication')),

     path('analytics/', include('Analytics.urls')),
]

FisheryManagement/Authentication/models.py
from django.db import models

# Create your models here.

FisheryManagement/Authentication/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User, Group
from django.db import IntegrityError

market_checker_group, _ = Group.objects.get_or_create(name='Market Checker')
pmanager_group, _ = Group.objects.get_or_create(name='PManager')
ISadmin_group, _ = Group.objects.get_or_create(name='ISAdmin')

def isLandingPage(request):
    return render(request, 'ISlandingPage.html')

def isMCLandingPage(request):
    return render(request, 'MCLandingPage.html')

def islogin(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            if user.groups.filter(name='Isadmin').exists() or user.groups.filter(name='PManager').exists():
                messages.error(request, 'You are not a Market Checker!')
            else:
                login(request, user)
                return redirect('Analytics:recentlist')
        else:
            messages.error(request, 'Username and Password are Invalid!')

    return render(request, 'index.html', {'password_reset_url': 'password_reset'})

def isreghtml(request):
    if request.method == 'POST':
        firstname = request.POST.get('fname')
        lastname = request.POST.get('lname')
        uname = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')

        if password != confirm_password:
            messages.error(request, 'Your password and confirm password are not match')
        else:
            try:
                my_user = User.objects.create_user(first_name=firstname, last_name=lastname, email=email, username=uname, password=password)
                my_user.save()
                messages.success(request, 'User Account Created successfully!')

                if not my_user.groups.filter(name='PManager').exists() and not my_user.groups.filter(name='ISAdmin').exists():
                    market_checker_group.user_set.add(my_user)

                return redirect('Authentication:login')  
            except IntegrityError:
                messages.error(request, 'Username or email already exist!')

    return render(request, 'register.html')

def ispmloginhtml(request): 
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            if user.groups.filter(name='Market Checker').exists() or user.groups.filter(name='ISAdmin').exists():
                 messages.error(request, 'You are not a Port Manager!')
            else:
                login(request, user)
                return redirect('Analytics:OverallCatchdash')
        else:
             messages.error(request, 'Username and Password are Invalid!')

    return render(request, 'PManager.html')

def ispmreghtml(request):
    if request.method == 'POST':
        firstname = request.POST.get('fname')
        lastname = request.POST.get('lname')
        uname = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')

        if password != confirm_password:
            messages.error(request, 'Your password and confirm password are not match')
        else:
            try:
                my_user = User.objects.create_user(first_name=firstname, last_name=lastname, email=email, username=uname, password=password)
                my_user.save()

                if not my_user.groups.filter(name='ISAdmin').exists() and not my_user.groups.filter(name='Market Checker').exists():
                    pmanager_group.user_set.add(my_user)

                messages.success(request, 'User Account Created successfully!')
                return redirect('Authentication:pmlogin')
            except IntegrityError:
                messages.error(request, 'Username or email already exist!')

    return render(request, 'PMregister.html')

def isadminloginhtml(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            if user.groups.filter(name='Market Checker').exists() or user.groups.filter(name='PManager').exists():
                 messages.error(request, 'You are not an Admin!')
            else:
                login(request, user)
                return redirect('Analytics:admindashboard')
        else:
             messages.error(request, 'Username and Password are Invalid!')

    return render(request, 'admin.html')

def isadminreghtml(request):
    if request.method == 'POST':
        firstname = request.POST.get('fname')
        lastname = request.POST.get('lname')
        uname = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')

        if password != confirm_password:
             messages.error(request, 'Your password and confirm password are not match')
        else:
            try:
                my_user = User.objects.create_user(first_name=firstname, last_name=lastname, email=email, username=uname, password=password)
                my_user.save()

                if not my_user.groups.filter(name='PManager').exists() and not my_user.groups.filter(name='Market Checker').exists():
                    ISadmin_group.user_set.add(my_user)

                messages.success(request, 'User Account Created successfully!')
                return redirect('Authentication:loginadmin') 
            
            except IntegrityError:
                messages.error(request, 'Username or email already exist!') 

    return render(request, 'adminreg.html')

FisheryManagement/Authentication/templates/ISlandingPage.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> IsdaanIS</title> 
    <link rel="stylesheet" href="{% static 'css/landingPage.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"/>
   </head>
<body>
  <nav>
    <div class="menu">
      <div class="logo">
        <img src="{% static 'img/pfda.png' %}" alt="pfda">
        <a href="#">IsdaanIS</a>
  </nav>
  <div class="img"></div>
  <div class="center">
    <img align="right" src="{% static 'img/fish.png' %}" alt="Fish">
    <div class="title">Welcome to IsdaanIS</div>
    <h3>A system made for Philippine Fisheries Development Authority</h3>
    <div class="btns">
      <a href="{% url 'Authentication:pmlogin' %}">
        <button>Login</button>
      </a>
      
      <button>Register</button>
    </div>
  </div>
</body>
</html>

FisheryManagement/Authentication/templates/MCLandingPage.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> IsdaanIS: Market Checker</title> 
    <link rel="stylesheet" href="{% static 'css/landingPage.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"/>
   </head>
<body>
  <nav>
    <div class="menu">
      <div class="logo">
        <img src="{% static 'img/pfda.png' %}" alt="pfda"> 
        <a href="#">IsdaanIS</a>
  </nav>
  <div class="img"></div>
  <div class="center">
    <img align="right" src="{% static 'img/fish.png' %}" alt="Fish">
    <div class="title">Welcome to IsdaanIS</div>
    <h3>A system made for Philippine Fisheries Development Authority</h3>
    <div class="btns">
      <a href="{% url 'Authentication:login' %}">
        <button>Login</button>
      </a>
      <a href="{% url 'Authentication:register' %}">
      <button>Register</button>
      </a>
    </div>
  </div>
</body>
</html>

FisheryManagement/Authentication/templates/PManager.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ISdaanIS: Port Manager</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/ISstyle.css' %}">
</head>
<body>

<nav class="navbar">
  <div class="container">
    <a class="navbar-brand" href="{% url 'Authentication:landingPage' %}">
      <img src="{% static 'img/pfda.png' %}" width="50px" alt="">
      ISdaanIS
    </a>
    <h2 class="navbar-text">PORT MANAGER LOGIN FORM</h2>
  </div>
</nav>

<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-6" id="column">

      <div class="card">
        <div class="card-header">
          <h2 class="card-title">Login</h2>
        </div>
        <div class="card-body">
          {% if messages %}
            {% for message in messages %}
              {% if message.tags == 'error' %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                  {{message}}
                </div>
              {% endif %}
            {% endfor %}
          {% endif %}
          

          <form action="{% url 'Authentication:pmlogin' %}" method="POST">
            {% csrf_token %}
            <div class="mb-3">
              <label for="username" class="form-label">Username:</label>
              <input type="text" class="form-control" id="username" name="username" required>
            </div>

            <div class="mb-3">
              <label for="password" class="form-label">Password:</label>
              <input type="password" class="form-control" id="password" name="password" required>
            </div>

            <div class="mb-3 form-check">
              <input type="checkbox" class="form-check-input" id="rememberMe">
              <label class="form-check-label" for="rememberMe">Remember me</label>
            </div>

            <div class="btn-container">
            <button type="submit" class="btn" id="login-btn">Login</button>
            </div>

            <div class="mt-3" id="login-register">
              <p>Don't have an account? <a href="{% url 'Authentication:pmregister' %}" class="login-link">Register</a></p>
            </div>
          </form>
        </div>
      </div>
      
    </div>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" ></script>
</html>

FisheryManagement/Authentication/templates/PMregister.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ISdaanIS: Port Manager</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/ISstyle.css' %}">
</head>
<body>

<nav class="navbar">
  <div class="container">
    <a class="navbar-brand" href="{% url 'Authentication:landingPage' %}">
      <img src="{% static 'img/pfda.png' %}" width="50px" alt="">
      ISdaanIS
    </a>
    <h2 class="navbar-text">PORT MANAGER REGISTRATION FORM</h2>
  </div>
</nav>

<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-6" id="column">

      <div class="card">
        <div class="card-header">
          <h2 class="card-title">REGISTER</h2>
        </div>
        <div class="card-body">
          {% if messages %}
            {% for message in messages %}
              {% if message.tags == 'error' %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                  {{message}}
                </div>
              {% endif %}
            {% endfor %}
          {% endif %}

          <form class="row g-3" action="{% url 'Authentication:pmregister' %}" method="POST">
            {% csrf_token %}
            <div class="col-md-6" id="input-fname">
              <label for="fname" class="form-label">First Name:</label>
              <input type="text" class="form-control" id="fname" name="fname" required>
            </div>

            <div class="col-md-6" id="input-lname">
              <label for="lname" class="form-label">Last Name:</label>
              <input type="text" class="form-control" id="lname" name="lname" required>
            </div>

            <div class="mb-3" id="input-email">
              <label for="email" class="form-label">Email:</label>
              <input type="email" class="form-control" id="email" name="email" required>
            </div>

            <div class="mb-3" id="input-username">
              <label for="username" class="form-label">Username:</label>
              <input type="text" class="form-control" id="username" name="username" required>
            </div>

            <div class="col-md-6" id="input-pass">
              <label for="password" class="form-label">Password:</label>
              <input type="password" class="form-control" id="password" name="password" required>
            </div>

            <div class="col-md-6" id="input-confirm_pass">
              <label for="confirm_password" class="form-label">Confirm Password:</label>
              <input type="password" class="form-control" id="confirm_password" name="confirm_password" required>
            </div>

            <div class="btn-container">
            <button type="submit" class="btn" id="login-btn">Register</button>
            </div>

            <div class="mt-3" id="login-register">
              <p>Already have an account?<a href="{% url 'Authentication:login' %}"class="register-link">Login</a></p> 
            </div>
          </form>
        </div>
      </div>
      
    </div>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" ></script>
</html>

FisheryManagement/Authentication/templates/admin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ISdaanIS: Admin</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/ISstyle.css' %}">
</head>
<body>

<nav class="navbar">
  <div class="container">
    <a class="navbar-brand" href="#">
      <img src="{% static 'img/pfda.png' %}" width="50px" alt="">
      ISdaanIS
    </a>
    <h2 class="navbar-text">ADMIN LOGIN FORM</h2>
  </div>
</nav>

<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-6" id="column">

      <div class="card">
        <div class="card-header">
          <h2 class="card-title">Login</h2>
        </div>
        <div class="card-body">
          {% if messages %}
            {% for message in messages %}
              {% if message.tags == 'error' %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                  {{message}}
                </div>
              {% endif %}
            {% endfor %}
          {% endif %}

          <form action="{% url 'Authentication:loginadmin' %}" method="POST">
            {% csrf_token %}
            <div class="mb-3">
              <label for="username" class="form-label">Username:</label>
              <input type="text" class="form-control" id="username" name="username" required>
            </div>

            <div class="mb-3">
              <label for="password" class="form-label">Password:</label>
              <input type="password" class="form-control" id="password" name="password" required>
            </div>

            <div class="mb-3 form-check">
              <input type="checkbox" class="form-check-input" id="rememberMe">
              <label class="form-check-label" for="rememberMe">Remember me</label>
            </div>

            <div class="btn-container">
            <button type="submit" class="btn" id="login-btn">Login</button>
            </div>

            <div class="mt-3" id="login-register">
              <p>Don't have an account? <a href="{% url 'Authentication:registeradmin' %}" class="login-link">Register</a></p>
            </div>
          </form>
        </div>
      </div>
      
    </div>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" ></script>
</html>

FisheryManagement/Authentication/templates/adminreg.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ISdaanIS: Admin</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/ISstyle.css' %}">
</head>
<body>

<nav class="navbar">
  <div class="container">
    <a class="navbar-brand" href="#">
      <img src="{% static 'img/pfda.png' %}" width="50px" alt="">
      ISdaanIS
    </a>
    <h2 class="navbar-text">ADMIN REGISTRATION FORM</h2>
  </div>
</nav>

<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-6" id="column">

      <div class="card">
        <div class="card-header">
          <h2 class="card-title">REGISTER</h2>
        </div>
        <div class="card-body">
          {% if messages %}
            {% for message in messages %}
              {% if message.tags == 'error' %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                  {{message}}
                </div>
              {% endif %}
            {% endfor %}
          {% endif %}

          <form class="row g-3" action="{% url 'Authentication:registeradmin' %}" method="POST">
            {% csrf_token %}
            <div class="col-md-6" id="input-fname">
              <label for="fname" class="form-label">First Name:</label>
              <input type="text" class="form-control" id="fname" name="fname" required>
            </div>

            <div class="col-md-6" id="input-lname">
              <label for="lname" class="form-label">Last Name:</label>
              <input type="text" class="form-control" id="lname" name="lname" required>
            </div>

            <div class="mb-3" id="input-email">
              <label for="email" class="form-label">Email:</label>
              <input type="email" class="form-control" id="email" name="email" required>
            </div>

            <div class="mb-3" id="input-username">
              <label for="username" class="form-label">Username:</label>
              <input type="text" class="form-control" id="username" name="username" required>
            </div>

            <div class="col-md-6" id="input-pass">
              <label for="password" class="form-label">Password:</label>
              <input type="password" class="form-control" id="password" name="password" required>
            </div>

            <div class="col-md-6" id="input-confirm_pass">
              <label for="confirm_password" class="form-label">Confirm Password:</label>
              <input type="password" class="form-control" id="confirm_password" name="confirm_password" required>
            </div>

            <div class="btn-container">
            <button type="submit" class="btn" id="login-btn">Register</button>
            </div>

            <div class="mt-3" id="login-register">
              <p>Already have an account?<a href="{% url 'Authentication:loginadmin' %}"class="register-link">Login</a></p> 
            </div>
          </form>
        </div>
      </div>
      
    </div>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" ></script>
</html>

FisheryManagement/Authentication/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ISdaanIS: Market Checker</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/ISstyle.css' %}">
</head>
<body>

<nav class="navbar">
  <div class="container">
    <a class="navbar-brand" href="{% url 'Authentication:landingPage' %}">
      <img src="{% static 'img/pfda.png' %}" width="50px" alt="">
      ISdaanIS
    </a>
    <h2 class="navbar-text">MARKET CHECKER LOGIN FORM</h2>
  </div>
</nav>

<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-6" id="column">

      <div class="card">
        <div class="card-header">
          <h2 class="card-title">Login</h2>
        </div>
        <div class="card-body">
          {% if messages %}
            {% for message in messages %}
              {% if message.tags == 'error' %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                  {{message}}
                </div>
              {% endif %}
            {% endfor %}
          {% endif %}

          <form action="{% url 'Authentication:login' %}" method="POST">
            {% csrf_token %}
            <div class="mb-3" id="input-username">
              <label for="username" class="form-label">Username:</label>
              <input type="text" class="form-control" id="username" name="username" required>
            </div>

            <div class="mb-3" id="input-pass">
              <label for="password" class="form-label">Password:</label>
              <input type="password" class="form-control" id="password" name="password" required>
            </div>

            <div class="mb-3 form-check">
              <input type="checkbox" class="form-check-input" id="rememberMe">
              <label class="form-check-label" for="rememberMe">Remember me</label>
            </div>

            <div class="btn-container">
            <button type="submit" class="btn" id="login-btn">Login</button>
            </div>

            <div class="mt-3" id="login-register">
              <p>Don't have an account? <a href="{% url 'Authentication:register' %}" class="login-link">Register</a></p>
            </div>
            
            <div class="mt-3" id="forgot-pass">
              <p>Did you forget your password? <a href="{% url 'Authentication:password_reset' %}">Forgot Password</a></p>
          </div>
          
          
          


          </form>
        </div>
      </div>
      
    </div>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" ></script>
</html>

FisheryManagement/Authentication/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ISdaanIS: Market Checker</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/ISstyle.css' %}">
</head>
<body>

<nav class="navbar">
  <div class="container">
    <a class="navbar-brand" href="{% url 'Authentication:landingPage' %}">
      <img src="{% static 'img/pfda.png' %}" width="50px" alt="">
      ISdaanIS
    </a>
    <h2 class="navbar-text">MARKET CHECKER REGISTRATION FORM</h2>
  </div>
</nav>

<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-6" id="column">

      <div class="card">
        <div class="card-header">
          <h2 class="card-title">Register</h2>
        </div>
        <div class="card-body">
          {% if messages %}
            <ul class="messages">
              {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
              {% endfor %}
            </ul>
          {% endif %}

          <form class="row g-3" action="{% url 'Authentication:register' %}" method="POST">
            {% csrf_token %}
            <div class="col-md-6" id="input-fname">
              <label for="fname" class="form-label">First Name:</label>
              <input type="text" class="form-control" id="fname" name="fname" required>
            </div>

            <div class="col-md-6" id="input-lname">
              <label for="lname" class="form-label">Last Name:</label>
              <input type="text" class="form-control" id="lname" name="lname" required>
            </div>

            <div class="mb-3" id="input-email">
              <label for="email" class="form-label">Email:</label>
              <input type="email" class="form-control" id="email" name="email" required>
            </div>

            <div class="mb-3" id="input-username">
              <label for="username" class="form-label">Username:</label>
              <input type="text" class="form-control" id="username" name="username" required>
            </div>

            <div class="col-md-6" id="input-pass">
              <label for="password" class="form-label">Password:</label>
              <input type="password" class="form-control" id="password" name="password" required>
            </div>

            <div class="col-md-6" id="input-confirm_pass">
              <label for="confirm_password" class="form-label">Confirm Password:</label>
              <input type="password" class="form-control" id="confirm_password" name="confirm_password" required>
            </div>

            <div class="btn-container">
              <button type="submit" class="btn" id="login-btn">Register</button>
            </div>

            <div class="mt-3" id="login-register">
              <p>Already have an account?<a href="{% url 'Authentication:login' %}" class="register-link">Login</a></p> 
            </div>
          </form>
        </div>
      </div>
      
    </div>
  </div>
</div>

<script src="{% static 'js/ISjs.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" ></script>
</body>
</html>